module.exports = {
  docs: [
    "introduction",
    "setup",
    "basics",
    "generative-model",
    "nearest-neighbor",
    "linear-regression",
    "ridge-regression",
    "logistic-regression",
    "pca",
    "svm",
    "k-means",
    "hierarchical-clustering",
    "random-forrest",
    "boosting",
    "resources",
    "license",
  ],
};
